server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy all API requests to Express backend
    location /api/ {
        proxy_pass http://150.240.166.229:4000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "";
    }

    # React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}

# temp dirs for OpenShift random UID
client_body_temp_path /tmp/nginx_temp/client_body;
proxy_temp_path        /tmp/nginx_temp/proxy;
fastcgi_temp_path      /tmp/nginx_temp/fastcgi;
uwsgi_temp_path        /tmp/nginx_temp/uwsgi;
scgi_temp_path         /tmp/nginx_temp/scgi;