apiVersion: v1
kind: Service
metadata:
  name: retail-frontend
  namespace: NAMESPACE_PLACEHOLDER
spec:
  selector:
    app: retail-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
