apiVersion: v1
kind: Namespace
metadata:
  name: techxchange
  labels:
    environment: techxchange
    app.kubernetes.io/environment: techxchange

    # Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted