apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retail-postgres-pvc
  namespace: NAMESPACE_PLACEHOLDER
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: STORAGE_CLASS_PLACEHOLDER
  resources:
    requests:
      storage: 5Gi
